name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Dar permisos al script de build
        run: chmod +x ./build.sh

      - name: Instalar dependencias (ejemplo para kernel de Android)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex libssl-dev make \
            libc6-dev libncurses5-dev \
            gcc build-essential \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            git

      - name: Ejecutar compilación
        run: ./build.sh
