name: Kernel CI Build (r8s KSU)

on:
  workflow_dispatch: # lo lanzas manualmente desde la pestaña "Actions"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      MODEL: r8s
      KSU_OPTION: y
      RECOVERY_OPTION: n
      CCACHE_OPTION: n
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential git zip unzip cpio bc curl python3 python3-pip \
            device-tree-compiler rsync libssl-dev wget liblz4-tool zstd \
            bc binutils-dev libelf-dev

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script (MODEL=r8s, KSU=y, Recovery=n, CCache=n)
        run: |
          set -o pipefail
          ./build.sh --model "${MODEL}" --ksu "${KSU_OPTION}" --recovery "${RECOVERY_OPTION}" --ccache "${CCACHE_OPTION}" 2>&1 | tee build.log

      - name: Show build log tail
        if: always()
        run: tail -n 200 build.log || true

      - name: Upload build artifacts (zips and images)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-r8s-ksu-${{ github.run_id }}
          path: |
            build/out/**
            build.log
