name: Build Kernel for r8s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias necesarias
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential ccache curl flex git libssl-dev \
          libncurses5-dev make python3 unzip wget zip \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
          libelf-dev libncurses-dev

    - name: Dar permisos al script de build
      run: chmod +x ./build.sh

    - name: Ejecutar build.sh para r8s
      run: |
        ./build.sh \
          --model r8s \
          --ksu y \
          --recovery n \
          --ccache n

    - name: Buscar archivo ZIP generado
      id: find_zip
      run: |
        ZIP_FILE=$(find build/out/r8s -name "*.zip" | head -n 1)
        echo "ZIP_PATH=$ZIP_FILE" >> $GITHUB_ENV

    - name: Subir artefacto
      if: env.ZIP_PATH != ''
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-r8s
        path: ${{ env.ZIP_PATH }}
